App\Entity\Settings:
  properties:
    name:
      - NotBlank: { message: 'The name field is required' }
      - Length:
              min: 2
              max: 20
              minMessage: 'Your  name must be at least {{ limit }} characters long'
              maxMessage: 'Your name cannot be longer than {{ limit }} characters'

    value:
        - NotBlank: { message: 'The value field is required' }
        - Length:
            min: 2
            max: 20
            minMessage: 'Your  value must be at least {{ limit }} characters long'
            maxMessage: 'Your value cannot be longer than {{ limit }} characters'

App\Entity\Category:
  properties:
    name:
      - NotBlank: { message: 'The name field is required' }
      - Length:
          min: 2
          max: 10
          minMessage: 'Your  name must be at least {{ limit }} characters long'
          maxMessage: 'Your name cannot be longer than {{ limit }} characters'