App\Entity\Settings:
  properties:
    name:
      - NotBlank: { message: 'The name field is required' }
      - Length:
              min: 2
              max: 20
              minMessage: 'Your  name must be at least {{ limit }} characters long'
              maxMessage: 'Your name cannot be longer than {{ limit }} characters'

    value:
        - NotBlank: { message: 'The value field is required' }
        - Length:
            min: 2
            max: 20
            minMessage: 'Your  value must be at least {{ limit }} characters long'
            maxMessage: 'Your value cannot be longer than {{ limit }} characters'

App\Entity\Category:
  properties:
    name:
      - NotBlank: { message: 'The name field is required' }
      - Length:
          min: 2
          max: 10
          minMessage: 'Your  name must be at least {{ limit }} characters long'
          maxMessage: 'Your name cannot be longer than {{ limit }} characters'

App\Entity\Product:
  properties:
    name:
      - NotBlank: { message: 'The name field is required' }
      - Length:
          min: 2
          max: 10
          minMessage: 'Your  name must be at least {{ limit }} characters long'
          maxMessage: 'Your name cannot be longer than {{ limit }} characters'

    price:
      - NotBlank: { message: 'The price field is required' }

    category:
      - NotBlank: { message: 'The category field is required' }

App\Entity\Customer:
  properties:
    name:
      - NotBlank: { message: 'The name field is required' }
    address:
        - NotBlank: { message: 'The address field is required' }
    city:
      - NotBlank: { message: 'The city field is required' }

    contact:
      - NotBlank: { message: 'The contact field is required' }

App\Entity\Invoice:
  properties:
    BillNumber:
      - NotBlank: { message: 'The BillNumber field is required' }
    BillDate:
      - NotBlank: { message: 'The BillDate field is required' }